exclude_paths:
  - tmp
  - vendor

detectors:
  DuplicateMethodCall:
    exclude:
      - Functionable#self.extended
  LongParameterList:
    enabled: false
  TooManyStatements:
    exclude:
      - Functionable#self.extended
